CREATE TABLE LANCAMENTO(
	ID INTEGER 
		GENERATED ALWAYS 
		AS IDENTITY
		PRIMARY KEY,

	DATA_LANCAMENTO DATE NOT NULL,

	VALOR NUMERIC(12,2) NOT NULL 
		CONSTRAINT ck_lancamento_valor
		CHECK(VALOR > 0), 

	TIPO VARCHAR(10) NOT NULL
		CONSTRAINT ck_lancamento_tipo
		CHECK(TIPO IN ('RECEITA', 'DESPESA')),

	CATEGORIA VARCHAR(20) NOT NULL,

	MEIO_DE_MOVIMENTACAO VARCHAR(20) NOT NULL,

	CONSTRAINT ck_lancamento_tipo_categoria
	CHECK(
		(
			TIPO = 'RECEITA'
			AND CATEGORIA IN ('EMPREGO', 'FREELANCE', 'PRESENTE')
		)
		OR
		(
			TIPO = 'DESPESA'
			AND CATEGORIA IN ('MERCADO', 'CONTAS', 'BELEZA', 'LAZER', 'FARMACIA')
		)
	),

	CONSTRAINT ck_lancamento_tipo_meio_de_movimentacao
	CHECK(
		(
			TIPO = 'RECEITA'
			AND MEIO_DE_MOVIMENTACAO IN ('PIX', 'DINHEIRO', 'TRANSFERENCIA')
		)
		OR
		(
			TIPO = 'DESPESA'
			AND MEIO_DE_MOVIMENTACAO IN ('DEBITO', 'CREDITO','PIX', 'DINHEIRO', 'TRANSFERENCIA')
		)
	)
);